spring:
    datasource:
      url: jdbc:mysql://116.62.56.23:3306/paydb-dev?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=UTC
      username: xsy-test
      password: Ov72ZzZqS33ox8xG0vqR
      #schema: database/import.sql
      #sql-script-encoding: utf-8
      driver-class-name: com.mysql.jdbc.Driver

    jpa:
      database: mysql
      show-sql: true
      hibernate:
        ddl-auto: update
        naming:
          strategy: org.hibernate.cfg.DefaultComponentSafeNamingStrategy
      properties:
         hibernate:
            dialect: org.hibernate.dialect.MySQL5Dialect